# Generated by Django 5.1.2 on 2024-11-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_view_product', 'Can view product'), ('can_add_product', 'Can add product'), ('can_change_product', 'Can change product'), ('can_delete_product', 'Can delete product')]},
        ),
    ]
